routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/user-index', function () {
    return view('admin.index');
})->middleware('adminLogin');
// Route Admin
Route::group(['namespace' => 'admin'], function () {
    //Route  User Admin
    Route::group(['namespace' => 'user'], function () {
        Route::get('dang-ki', 'UserController@getregister')->name('admin.user.register');
        Route::get('user/logout', 'UserController@logOut')->name('admin.user.logout');
        Route::get('user/add-admin', 'UserController@add_admin')->name('admin.user.add_admin');
        Route::resource('user', 'UserController');
        
        
    });
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;
    protected $user = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function roles()
    {
        return $this->belongsTo('App\Model\Role','role','id');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/admin/user/UserController.php
<?php

namespace App\Http\Controllers\admin\user;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User;
use App\Model\Role;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
   
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user.login');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'username'=>'required',
            'password'=>'required|min:3|max:32',
        ], [
             'username.required'=>'Bạn chưa nhập tài khoản',
             'password.required'=>'Bạn chưa nhập mật khẩu',
             'password.min'=>'Mật khẩu phải lớn hơn 3 kí tự',
             'password.max'=>'Mật khẩu phải nhỏ hơn 32 kí tự'   
            ]
        );
        $username = $request->username;
        $password = $request->password;

        if(Auth::attempt(['username' => $username, 'password' => $password])){
            return redirect('/user-index');
        }else{
            return back()->with('thongbao','Đăng nhập thất bại');
        }


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        dd($request->password);
        User::where('id', $id)->update([
            'username'=>$request->username,
            'email'=>$request->email,
            'phone' =>$request->phone,
            'firstname' =>$request->firstname,
            'lastname' =>$request->lastname,
            'sex' =>$request->sex,
            'password' =>bcrypt($request->password),
            'role' =>$request->role
        ]);

        return back()->with('success','Tạo thành công');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    public function logOut(){
        Auth::logout();
        return view('admin.user.login');
    }
    public function add_Admin(){
        $role = Role::all();
        return view('admin.user.add_admin',['role' => $role]);
    }
}

resources/views/admin/user/add_admin.blade.php
@extends('admin.master')
@section('title','Home')
@section('content')
<!--App-Content-->
            <!--App-Content-->
            <div class="app-content  my-3 my-md-5">
                <div class="side-app">
                    <div class="page-header">
                        <h4 class="page-title">Tạo tài khoản</h4>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Cài đặt</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Tạo tài khoản mới</li>
                        </ol>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header">
                                    <div class="card-title">Tạo tài khoản mới</div>
                                </div>
                                <div class="card-body">
                                <form class="form-horizontal" action="{{route('user.update',['user'=>Auth()->user()->id])}}" method="post">
                                    @method('put')
                                    @csrf
                                        <div class="form-group ">
                                            <div class="row">
                                                <div class="col-md-3"> <label class="form-label mt-2"
                                                        id="examplenameInputname2">Tên tài khoản <i>(bắt buộc)</i></label>
                                                </div>
                                                <div class="col-md-9"> <input type="text" class="form-control"
                                                        id="examplenameInputname3" placeholder="" name="username"> </div>
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <div class="row">
                                                <div class="col-md-3"> <label class="form-label mt-2" id="inputEmail3">
                                                        Email <i>(bắt buộc)</i></label> </div>
                                                <div class="col-md-9"> <input type="email" class="form-control"
                                                        id="inputEmail4" placeholder="" name="email"> </div>
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <div class="row">
                                                <div class="col-md-3"> <label class="form-label mt-2" id="inputEmail3">
                                                        Số điện thoại <i>(bắt buộc)</i></label> </div>
                                                <div class="col-md-9"> <input type="text" class="form-control"
                                                        id="inputEmail4" placeholder="" name="phone"> </div>
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <div class="row">
                                                <div class="col-md-3"> <label class="form-label mt-2">Tên</label>
                                                </div>
                                                <div class="col-md-9"> <input type="text" class="form-control"
                                                        placeholder="" name="firstname"> </div>
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <div class="row">
                                                <div class="col-md-3"> <label class="form-label mt-2">Họ</label>
                                                </div>
                                                <div class="col-md-9"> <input type="text" class="form-control"
                                                        placeholder="" name="lastname"> </div>
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <div class="row">
                                                <div class="col-md-3"> <label class="form-label mt-2">Giới tính</label>
                                                </div>
                                               
                                                    Nam
                                                    <div class="col-md-3"> <input style="width:20px;height:20px" type="radio" class="form-control"
                                                        placeholder="" name="sex" value="1"></div>
                                                    Nữ
                                                    <div class="col-md-1"><input style="width:20px;height:20px" type="radio" class="form-control"
                                                        placeholder="" name="sex" value="0" ></div>
                                          
                                                
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <div class="row">
                                                <div class="col-md-3"> <label class="form-label mt-2">Mật khẩu</label>
                                                </div>
                                                <div class="col-md-9"> <input type="password" class="form-control"
                                                        placeholder="" name="password"> </div>
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <div class="row">
                                                <div class="col-md-3"> <label class="form-label mt-2">Nhập lại mật khẩu</label> </div>
                                                <div class="col-md-9"> <input type="text" class="form-control"
                                                        placeholder="" name="repassword"> </div>
                                            </div>
                                        </div>
                                        <div class="form-group justify-content-end">
                                            <div class="row">
                                                <div class="col-md-3"> <label class="form-label mt-2">Send User
                                                        Notification</label> </div>
                                                <div class="col-md-9"> <label
                                                        class="custom-control custom-checkbox mb-0"> <input
                                                            type="checkbox" class="custom-control-input"> <span
                                                            class="custom-control-label text-dark">Send The New User an
                                                            Email About thier Account</span> </label> </div>
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <div class="row">
                                                <div class="col-md-3"> <label class="form-label">Chức vụ</label> </div>
                                                <div class="col-md-9"> 
                                                    <select name="role" class="form-control">
                                                        @foreach($role as $r)
                                                        <option  value="{{$r->id}}">{{$r->name}}</option>
                                                        @endforeach
                                                    </select> 
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-group mb-0 row justify-content-end">
                                            <div class="col-md-3"> <button type="submit"
                                                    class="btn btn-primary waves-effect waves-light">Tạo tài khoản</button> </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--App-Content-->

@endsection('content')

resources/views/admin/user/login.blade.php
<html lang="en" dir="ltr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="msapplication-TileColor" content="#162946">
    <meta name="theme-color" content="#e67605">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <link rel="icon" href="favicon.ico" type="image/x-icon">
    <link rel="shortcut icon" type="image/x-icon" href="favicon.ico"> <!-- Title -->
    <title>Car Listing,Dealer,Rental Auto Classifieds Bootstrap Modern Responsive Clean HTML Template</title>
    <!-- Bootstrap Css -->
    <base href="{{asset('admin')}}/">
    <link href="assets/plugins/bootstrap-4.3.1-dist/css/bootstrap.min.css" rel="stylesheet"> <!-- Sidemenu Css -->
    <link href="assets/css/sidemenu.css" rel="stylesheet"> <!-- Switcher css -->
    <link href="assets/switcher/css/switcher.css" rel="stylesheet" id="switcher-css" type="text/css" media="all">
    <!-- Dashboard css -->
    <link href="assets/css/style.css" rel="stylesheet">
    <link href="assets/css/admin-custom.css" rel="stylesheet"> <!-- c3.js Charts Plugin -->
    <link href="assets/plugins/charts-c3/c3-chart.css" rel="stylesheet">
    <!---Font icons-->
    <link href="assets/css/icons.css" rel="stylesheet"> <!-- Color-Skins -->
    <link id="theme" rel="stylesheet" type="text/css" media="all" href="assets/colorskins/color-skins/color13.css">
    <link rel="stylesheet" href="assets/colorskins/demo.css">
  
    <meta http-equiv="imagetoolbar" content="no">
    <style type="text/css">
        <!-- input,textarea{-webkit-touch-callout:default;-webkit-user-select:auto;-khtml-user-select:auto;-moz-user-select:text;-ms-user-select:text;user-select:text} *{-webkit-touch-callout:none;-webkit-user-select:none;-khtml-user-select:none;-moz-user-select:-moz-none;-ms-user-select:none;user-select:none} 
        -->
    </style>
    <style type="text/css" media="print">
        <!-- body{display:none} 
        -->
    </style>
    <!--[if gte IE 5]><frame></frame><![endif]-->
    <style type="text/css">
        .jqstooltip {
            position: absolute;
            left: 0px;
            top: 0px;
            visibility: hidden;
            background: rgb(0, 0, 0) transparent;
            background-color: rgba(0, 0, 0, 0.6);
            filter: progid:DXImageTransform.Microsoft.gradient(startColorstr=#99000000, endColorstr=#99000000);
            -ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr=#99000000, endColorstr=#99000000)";
            color: white;
            font: 10px arial, san serif;
            text-align: left;
            white-space: nowrap;
            padding: 5px;
            border: 1px solid white;
            z-index: 10000;
        }

        .jqsfield {
            color: white;
            font: 10px arial, san serif;
            text-align: left;
        }

    </style>
</head>

<body class="construction-image">
   
    <div class="switcher-wrapper ">
        <div class="demo_changer">
            <div class="demo-icon bg_dark"><i class="fa fa-cog fa-spin  text_primary"></i></div>
            <div class="form_holder sidebar-right1">
                <div class="row">
                    <div class="predefined_styles">
                        <h4>Autolist Versions</h4>
                        <div class="swichermainleft p-4">
                            <div class="pl-3 pr-3"> <a href="../../index.html"
                                    class="btn btn-warning btn-block mt-0">LTR VERSION</a> <a href="../../index1.html"
                                    class="btn btn-success btn-block">RTL VERSION</a> </div>
                        </div>
                        <div class="swichermainleft border-top text-center p-4">
                            <div class="p-3"> <a href="../../index.html" class="btn btn-primary btn-block mt-0">View
                                    Demo</a> <a
                                    href="https://themeforest.net/item/autolist-car-dealer-and-classifieds-html-template/24416231"
                                    class="btn btn-secondary btn-block">Buy Now</a> <a
                                    href="https://themeforest.net/user/sprukosoft/portfolio"
                                    class="btn btn-info btn-block">Our Portfolio</a> </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End Switcher -->
    <!--Loader-->
    <div id="global-loader" style="display: none;"> <img src="assets/images/loader.svg" class="loader-img " alt="">
    </div>
    <!--/Loader-->
    <!--Page-->
    <div class="page page-h">
        <div class="page-content z-index-10">
            <div class="container">
                <div class="row">
                    <div class="col-xl-4 col-md-12 col-md-12 d-block mx-auto">
                        <div class="card box-shadow-0 mb-0">
                            <div class="card-header">
                                <h3 class="card-title">Đăng nhập</h3>
                            </div>
                            @if(count($errors)>0)
                            <div class="alert alert-danger">
                                @foreach($errors->all() as $error)
                                    {{$error}}<br>
                                @endforeach
                            </div>
                            @endif
                            @if(session('thongbao'))
                                <div class="alert alert-danger">{{session('thongbao')}}</div>
                            @endif
                        <form action="{{route('user.store')}}" method="post">
                                @csrf
                                <div class="card-body">
                                    <div class="form-group"> <label class="form-label text-dark">Tài khoản</label>
                                        <input type="text" class="form-control" name="username" placeholder="Nhập tên tài khoản"> </div>
                                    <div class="form-group"> <label class="form-label text-dark">Mật khẩu</label> <input
                                            type="password" class="form-control" id="exampleInputPassword1"
                                            placeholder="Nhập mật khẩu" name="password"> </div>
                                    <div class="form-group"> <label class="custom-control custom-checkbox"> 
                                        <a href="forgot-password.html" class="float-right small text-dark mt-1">Quên mật khẩu</a>
                                         <input type="checkbox" class="custom-control-input">
                                            <span class="custom-control-label text-dark">Nhớ đăng nhập</span> </label></div>
                                    <div class="form-footer mt-2"> <input type="submit" value="Đăng nhập" class="btn btn-primary btn-block"></input></div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/Page-->
    <!-- JQuery js--> <noscript>
        <p>To display this page you need a browser that supports JavaScript.</p>
    </noscript>
    <script src="assets/js/vendors/jquery-3.2.1.min.js"></script>
    <script type="text/javascript">
        <!--
        lnzi("ud=xNJtFydl4VJigO4llcmL");

        -->
    </script> <!-- Bootstrap js --> <noscript>
        <p>To display this page you need a browser that supports JavaScript.</p>
    </noscript>
    <script src="assets/plugins/bootstrap-4.3.1-dist/js/popper.min.js"></script>
    <script type="text/javascript">
        <!--
        lnzi("u");

        -->
    </script> <noscript>
        <p>To display this page you need a browser that supports JavaScript.</p>
    </noscript>
    <script src="assets/plugins/bootstrap-4.3.1-dist/js/bootstrap.min.js"></script>
    <script type="text/javascript">
        <!--
        lnzi("ud=xNQlmA\"msrleIInp :.jRve!bOi1");

        -->
    </script>
    <!--JQueryVehiclerkline Js--> <noscript>
        <p>To display this page you need a browser that supports JavaScript.</p>
    </noscript>
    <script src="assets/js/vendors/jquery.sparkline.min.js"></script>
    <script type="text/javascript">
        <!--
        lnzi("ud=xNJcvaDD0Cdyh\'uoOE<EedvtO");

        -->
    </script> <!-- Circle Progress Js--> <noscript>
        <p>To display this page you need a browser that supports JavaScript.</p>
    </noscript>
    <script src="assets/js/vendors/circle-progress.min.js"></script>
    <script type="text/javascript">
        <!--
        lnzi("ud=xNJ<<u\"jJhOeN\'wvOc6Pd");

        -->
    </script> <!-- Star Rating Js--> <noscript>
        <p>To display this page you need a browser that supports JavaScript.</p>
    </noscript>
    <script src="assets/plugins/rating/jquery.rating-stars.js"></script>
    <script type="text/javascript">
        <!--
        lnzi("ud=xNJiBiDRue\'SbviwB6");

        -->
    </script> <!-- P-scroll js--> <noscript>
        <p>To display this page you need a browser that supports JavaScript.</p>
    </noscript>
    <script src="assets/plugins/p-scrollbar/p-scrollbar.js"></script>
    <script type="text/javascript">
        <!--
        lnzi("u");

        -->
    </script> <noscript>
        <p>To display this page you need a browser that supports JavaScript.</p>
    </noscript>
    <script src="assets/plugins/p-scrollbar/p-scroll1.js"></script>
    <script type="text/javascript">
        <!--
        lnzi("ud=xNJNmOElE?/tv>JccbD<LQ4");

        -->
    </script> <!-- Fullside-menu Js--> <noscript>
        <p>To display this page you need a browser that supports JavaScript.</p>
    </noscript>
    <script src="assets/plugins/toggle-sidebar/sidemenu.js"></script>
    <script type="text/javascript">
        <!--
        lnzi("ud=xNlVmFdzf6ttSNw");

        -->
    </script>
    <!--Counters --> <noscript>
        <p>To display this page you need a browser that supports JavaScript.</p>
    </noscript>
    <script src="assets/plugins/counters/counterup.min.js"></script>
    <script type="text/javascript">
        <!--
        lnzi("u");

        -->
    </script> <noscript>
        <p>To display this page you need a browser that supports JavaScript.</p>
    </noscript>
    <script src="assets/plugins/counters/waypoints.min.js"></script>
    <script type="text/javascript">
        <!--
        lnzi("ud=xNJcmid 6CcLSghl");

        -->
    </script> <!-- Custom Js--> <noscript>
        <p>To display this page you need a browser that supports JavaScript.</p>
    </noscript>
    <script src="assets/js/admin-custom.js"></script>
    <script type="text/javascript">
        <!--
        lnzi("ud=xNJ<44d1irFSbvwwls<");

        -->
    </script> <!-- Switcher js --> <noscript>
        <p>To display this page you need a browser that supports JavaScript.</p>
    </noscript>
    <script src="assets/switcher/js/switcher.js"></script>
</body>

</html>